
package top.flyroc.received4server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crm4bos2cxf.flyroc.top/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<top.flyroc.received4server.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm4bos2cxf.flyroc.top/", className = "top.flyroc.received4server.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm4bos2cxf.flyroc.top/", className = "top.flyroc.received4server.FindAllResponse")
    public List<Customer> findAll();

}
